// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ImgGrid: typeof import('./src/components/imgGrid.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    Tabs: typeof import('./src/components/tabs.vue')['default']
  }
}
